'use strict';
const $=id=>document.getElementById(id), fmt=n=>n.toLocaleString('ru-RU');
let current,previous,operationData,operationPrev,data,outcomes;
let scheduleItems=[],taskItems=[];
const months=['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен'];
const fullMonths=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь'];
const periodIndices={year:[0,1,2,3,4,5,6,7,8],quarter:[6,7,8],month:[8]};
function getOutcomes(type,key){return outcomes[type][key]}
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options});let body;try{body=await response.json()}catch{throw new Error('Сервер вернул некорректный ответ')}if(!response.ok)throw new Error(body.error||'Не удалось получить данные');return body}
function statusMessage(message,error=false){$('apiStatus').textContent=message;$('apiStatus').classList.toggle('api-error',error);$('retryApi').hidden=!error}
function taskCount(){const count=taskItems.filter(t=>!t.completed).length;$('taskCount').textContent=count;$('navCount').textContent=count}
function renderTasks(){const box=$('taskList');box.innerHTML=taskItems.map(t=>`<div class="task"><label><input type="checkbox" data-task="${escapeHtml(t.id)}" ${t.completed?'checked':''}><span><b>${escapeHtml(t.title)}</b><small>${escapeHtml(t.detail)}</small></span></label><span class="tag ${['lime','purple','peach'].includes(t.color)?t.color:'purple'}">${escapeHtml(t.tag)}</span></div>`).join('');box.querySelectorAll('input').forEach(input=>input.onchange=async()=>{const task=taskItems.find(t=>t.id===input.dataset.task),old=Boolean(task.completed);input.disabled=true;try{const result=await api('/api/tasks/'+encodeURIComponent(task.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:input.checked})});task.completed=Boolean(result.completed);taskCount();statusMessage('Подключено к API · задача сохранена')}catch(e){input.checked=old;statusMessage(e.message,true)}finally{input.disabled=false}});taskCount()}
async function loadData(){statusMessage('Загружаем данные…');$('period').disabled=$('operationType').disabled=$('compare').disabled=true;try{const [dashboard,schedule,tasks]=await Promise.all([api('/api/dashboard'),api('/api/appointments'),api('/api/tasks')]);({current,previous,operationData,operationPrev,data,outcomes}=dashboard);scheduleItems=schedule.items;taskItems=tasks.items;render();renderDay(activeDay);renderTasks();statusMessage('Подключено к API · демонстрационная база');document.querySelector('footer>span').textContent='Обновлено '+new Date(dashboard.updatedAt).toLocaleString('ru-RU');$('period').disabled=$('operationType').disabled=$('compare').disabled=false}catch(e){statusMessage(e.message,true)}}
function sum(a){return a.reduce((s,x)=>s+x,0)}
function delta(a,b){return (a>=b?'+':'')+((b?(a/b-1)*100:0)).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%'}
function svgChart(values,prev,labels,kind){const W=580,H=210,left=32,right=18,top=14,bottom=30,plotW=W-left-right,plotH=H-top-bottom,max=Math.max(1,Math.ceil(Math.max(...values,...prev)/ (kind==='bars'?5:50))*(kind==='bars'?5:50));const x=i=>left+(i+.5)*plotW/values.length,y=v=>top+plotH-v/max*plotH;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${kind==='bars'?'Количество операций':'Количество приёмов'} по месяцам">`;for(let i=0;i<=3;i++){let yy=top+i*plotH/3;svg+=`<line x1="${left}" x2="${W-right}" y1="${yy}" y2="${yy}" stroke="#eeecf4" stroke-dasharray="3 5"/><text x="${left-8}" y="${yy+4}" text-anchor="end">${Math.round(max*(1-i/3))}</text>`}if(kind==='line'){const points=values.map((v,i)=>`${x(i)},${y(v)}`).join(' ');svg+=`<defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#6358e8" stop-opacity=".16"/><stop offset="100%" stop-color="#6358e8" stop-opacity="0"/></linearGradient></defs><polygon points="${x(0)},${top+plotH} ${points} ${x(values.length-1)},${top+plotH}" fill="url(#area)"/>`;if($('compare').checked)svg+=`<polyline points="${prev.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#d3d0e1" stroke-width="2.5" stroke-dasharray="5 5"/>`;svg+=`<polyline points="${points}" fill="none" stroke="#6254e8" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>`;values.forEach((v,i)=>svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="white" stroke="#6254e8" stroke-width="2"/>`)}values.forEach((v,i)=>{if(kind==='bars'){const w=Math.min(22,plotW/values.length*.23);if($('compare').checked)svg+=`<rect x="${x(i)-w-2}" y="${y(prev[i])}" width="${w}" height="${top+plotH-y(prev[i])}" rx="5" fill="#eae7f4"/>`;svg+=`<rect x="${x(i)+2}" y="${y(v)}" width="${w}" height="${top+plotH-y(v)}" rx="5" fill="${i===values.length-1?'#6254e8':'#b5a6ed'}"/><text x="${x(i)+w/2+2}" y="${y(v)-6}" text-anchor="middle">${v}</text>`}svg+=`<text x="${x(i)}" y="${H-6}" text-anchor="middle">${labels[i]}</text><rect class="hit" data-index="${i}" x="${left+i*plotW/values.length}" y="0" width="${plotW/values.length}" height="${H}" fill="transparent" opacity=".3"><title>${labels[i]} 2026: ${v}${$('compare').checked?`; 2025: ${prev[i]}`:''}</title></rect>`});return svg+'</svg>'}
function render(){const key=$('period').value,indices=periodIndices[key],d=data[key],type=$('operationType').value;const v=indices.map(i=>current[i]),pv=indices.map(i=>previous[i]),op=indices.map(i=>operationData[type][i]),pop=indices.map(i=>operationPrev[type][i]);const all=sum(indices.map(i=>operationData.all[i])),oldAll=sum(indices.map(i=>operationPrev.all[i]));$('petNum').textContent=fmt(d.pets);$('petDelta').textContent=delta(d.pets,d.petPrev);$('visitNum').textContent=fmt(sum(v));$('visitDelta').textContent=delta(sum(v),sum(pv));$('opNum').textContent=all;$('opDelta').textContent=delta(all,oldAll);$('visitTotal').textContent=fmt(sum(v))+' приёмов';$('opTotal').textContent=sum(op)+' операций';$('visitsChart').innerHTML=svgChart(v,pv,indices.map(i=>months[i]),'line');$('opsChart').innerHTML=svgChart(op,pop,indices.map(i=>months[i]),'bars');document.querySelectorAll('.prevLegend').forEach(e=>e.hidden=!$('compare').checked);$('firstVisits').textContent=d.first;$('repeatVisits').textContent=d.repeat;$('cancellations').innerHTML=`${d.cancel} <small>отмены</small> · ${d.noShow} <small>неявок</small>`;
const cats=[['Терапия',.44,'#6254e8'],['Хирургия',.31,'#b6a5ed'],['Профилактика',.17,'#d5ed9b'],['Другие',.08,'#ded9ea']];const counts=cats.map(c=>Math.round(c[1]*sum(v)));counts[3]=sum(v)-sum(counts.slice(0,3));$('structureBars').innerHTML=cats.map((c,i)=>`<div class="structure-row"><div><span>${c[0]}</span><span>${counts[i]} · ${Math.round(counts[i]/sum(v)*100)}%</span></div><div class="track"><div style="width:${counts[i]/sum(v)*100}%;background:${c[2]}"></div></div></div>`).join('');const results=getOutcomes(type,key,sum(op)),colors=['#514de8','#d6f584','#e9ad99','#e6e1f3'],names=['Без осложнений','С осложнениями','Летальный исход','Наблюдение продолжается'];let start=0;const segments=results.map((n,i)=>{const end=start+n/sum(op)*100;const s=`${colors[i]} ${start}% ${end}%`;start=end;return s});$('donut').style.background=`conic-gradient(${segments.join(',')})`;$('outcomeTotal').textContent=sum(op);$('outcomeSubtitle').textContent=type==='all'?'По всем операциям за выбранный период':$('operationType').selectedOptions[0].textContent+' · выбранный период';$('outcomeList').innerHTML=results.map((n,i)=>`<div class="outcome-row"><i style="background:${colors[i]}"></i><span>${names[i]}</span><strong>${n} <span style="font-weight:400;color:#a297ae">· ${Math.round(n/sum(op)*100)}%</span></strong></div>`).join('');
$('visitsChart').querySelectorAll('.hit').forEach(e=>e.addEventListener('click',()=>showMonth(indices[Number(e.dataset.index)],'visits')));$('opsChart').querySelectorAll('.hit').forEach(e=>e.addEventListener('click',()=>showMonth(indices[Number(e.dataset.index)],'ops')))}
function modal(title,html){$('detailTitle').textContent=title;$('detailBody').innerHTML=html;$('detail').showModal()}
function showMonth(i,kind){const type=$('operationType').value;modal(fullMonths[i]+' 2026',kind==='visits'?`<div class="detail-line"><b>${current[i]} проведённых приёмов</b><small>В том же месяце 2025 года: ${previous[i]}</small></div><div class="detail-line">${delta(current[i],previous[i])} к прошлому году</div><p>Сводка загружена из базы API. Для исторических приёмов сохранены агрегированные отчёты.</p>`:`<div class="detail-line"><b>${operationData[type][i]} операций</b><small>${$('operationType').selectedOptions[0].textContent}</small></div><div class="detail-line">2025: ${operationPrev[type][i]} · изменение ${delta(operationData[type][i],operationPrev[type][i])}</div><p>Сводка рассчитана API по демонстрационным записям операций в базе.</p>`)}
const dayNames=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];let counts=[0,0,0,0,0,0,0],activeDay=0;
function dayEntries(day){const date='2026-10-'+String(day+5).padStart(2,'0');return scheduleItems.filter(e=>e.date===date).map(e=>({...e,name:escapeHtml(e.name),info:escapeHtml(e.info),reason:escapeHtml(e.reason),duration:e.duration+' минут',color:e.kind==='Операция'?'#a397ed':e.kind==='Контроль'?'#c6de7b':'#514de8'}))}
function renderDay(day){counts=dayNames.map((_,i)=>dayEntries(i).length);activeDay=day;$('week').innerHTML=dayNames.map((name,i)=>`<button class="day ${i===day?'active':''}" data-day="${i}" aria-pressed="${i===day}"><span>${['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'][i]}</span><b>${i+5}</b><small>${counts[i]?counts[i]+' записей':'Выходной'}</small></button>`).join('');$('week').querySelectorAll('button').forEach(b=>b.onclick=()=>renderDay(Number(b.dataset.day)));$('dayTitle').textContent=dayNames[day]+', '+(day+5)+' октября';$('dayCount').textContent=counts[day]+' записей';const entries=dayEntries(day);$('appointments').innerHTML=entries.length?entries.map((e,i)=>`<button class="appointment" data-appt="${i}"><span class="time">${e.time}</span><i class="appt-marker" style="background:${e.color}"></i><span><strong>${e.name} <span style="font-weight:400;color:#a297af">· ${e.info}</span></strong><small>${e.reason} · ${e.duration}</small></span><span class="appt-type">${e.kind}</span></button>`).join(''):'<p style="color:#9690a6;padding:30px 0;text-align:center">В этот день нет записей. Выходной день.</p>';$('appointments').querySelectorAll('button').forEach(b=>b.onclick=()=>{const e=entries[Number(b.dataset.appt)];modal(e.name+' — запись на приём',`<div class="detail-line">${e.info}</div><div class="detail-line"><b>${dayNames[day]}, ${day+5} октября · ${e.time}</b><small>${e.reason} · ${e.duration}</small></div><div class="detail-line">Врач: Анна Смирнова</div><p style="color:#8b8099;font-size:13px">Это демонстрационная запись, не медицинская карта.</p>`)})}
$('period').onchange=render;$('compare').onchange=render;$('operationType').onchange=render;$('closeDialog').onclick=$('doneDialog').onclick=()=>$('detail').close();$('detail').onclick=e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close()}};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')});$('retryApi').onclick=loadData;loadData();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'set_dashboard_period',description:'Изменить период статистики в кабинете врача.',inputSchema:{type:'object',properties:{period:{type:'string',enum:['year','quarter','month']}},required:['period'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Object.hasOwn(periodIndices,input.period))throw new Error('Недопустимый период');if(!data)throw new Error('Данные ещё не загружены');$('period').value=input.period;render();return {period:input.period,pets:data?.[input.period]?.pets,visits:$('visitNum').textContent,operations:$('opNum').textContent}}},{signal:lifecycle.signal})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'read_week_schedule',description:'Прочитать демонстрационные записи врача на день следующей недели.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:0,maximum:6}},required:['day'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||!Number.isInteger(input.day)||input.day<0||input.day>6)throw new Error('Недопустимый день');return {day:dayNames[input.day],date:`${input.day+5} октября 2026`,appointments:dayEntries(input.day)}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
