const json=(value,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
function dbFor(env){if(!env.DB)throw new HttpError(503,'База данных временно недоступна');return env.DB}
async function initialize(db){if(await db.prepare('SELECT id FROM reports WHERE id = ?').bind('demo-v1').first())return;const statements=[];
statements.push(db.prepare('INSERT OR IGNORE INTO reports(id,payload) VALUES (?,?)').bind('demo-v1',JSON.stringify(SEED.report)));
const insertRows=(table,cols,rows)=>{const size=Math.floor(90/cols.length);for(let i=0;i<rows.length;i+=size){const chunk=rows.slice(i,i+size);statements.push(db.prepare(`INSERT OR IGNORE INTO ${table} (${cols.join(',')}) VALUES ${chunk.map(()=>`(${cols.map(()=>'?').join(',')})`).join(',')}`).bind(...chunk.flat()))}};
insertRows('patients',['id','name','info'],SEED.patients);insertRows('appointments',['id','patient_id','date','time','reason','kind','duration'],SEED.appointments);insertRows('operations',['id','year','month','type','outcome'],SEED.operations);insertRows('tasks',['id','title','detail','tag','color','completed'],SEED.tasks);await db.batch(statements)}
async function rows(db,sql,...args){return (await db.prepare(sql).bind(...args).all()).results}
async function dashboard(db){const report=JSON.parse((await db.prepare('SELECT payload FROM reports WHERE id=?').bind('demo-v1').first()).payload);const ops=await rows(db,'SELECT year,month,type,outcome,COUNT(*) AS count FROM operations GROUP BY year,month,type,outcome');for(const group of ['operationData','operationPrev'])report[group]={all:Array(9).fill(0),soft:Array(9).fill(0),ortho:Array(9).fill(0),dental:Array(9).fill(0)};report.outcomes={};for(const type of ['all','soft','ortho','dental']){report.outcomes[type]={};for(const key of ['year','quarter','month'])report.outcomes[type][key]=[0,0,0,0]}
for(const op of ops){const group=op.year===2026?'operationData':'operationPrev';report[group][op.type][op.month-1]+=op.count;report[group].all[op.month-1]+=op.count;if(op.year===2026){for(const type of ['all',op.type])for(const key of ['year',...(op.month>=7?['quarter']:[]),...(op.month===9?['month']:[])])report.outcomes[type][key][['clear','complication','death','pending'].indexOf(op.outcome)]+=op.count}}
return {...report,updatedAt:new Date().toISOString(),demo:true}}
async function api(request,env){const url=new URL(request.url),path=url.pathname,db=dbFor(env);if(request.method!=='GET'){const origin=request.headers.get('Origin');if(!origin||origin!==url.origin||request.headers.get('Sec-Fetch-Site')==='cross-site')throw new HttpError(403,'Недопустимый источник запроса');if(!request.headers.get('Content-Type')?.startsWith('application/json'))throw new HttpError(415,'Ожидается application/json')}
if(!['GET','PATCH'].includes(request.method))throw new HttpError(405,'Метод не поддерживается');if(path==='/api/health')return json({status:'ok',storage:'D1',demo:true});await initialize(db);
if(request.method==='GET'){
if(path==='/api/dashboard')return json(await dashboard(db));
if(path==='/api/patients')return json({items:await rows(db,'SELECT * FROM patients ORDER BY name'),demo:true});
if(path==='/api/appointments'){const date=url.searchParams.get('date');if(date&&!/^2026-10-(0[5-9]|1[01])$/.test(date))throw new HttpError(400,'Выберите дату с 5 по 11 октября 2026');return json({items:await rows(db,`SELECT a.*,p.name,p.info FROM appointments a JOIN patients p ON p.id=a.patient_id ${date?'WHERE a.date=?':''} ORDER BY a.date,a.time`,...(date?[date]:[])),weekStart:'2026-10-05',demo:true})}
if(path==='/api/operations'){const type=url.searchParams.get('type')||'all';if(!['all','soft','ortho','dental'].includes(type))throw new HttpError(400,'Неизвестный вид операции');return json({items:await rows(db,`SELECT * FROM operations ${type==='all'?'':'WHERE type=?'} ORDER BY year DESC,month DESC,id`,...(type==='all'?[]:[type])),demo:true})}
if(path==='/api/tasks')return json({items:await rows(db,'SELECT * FROM tasks ORDER BY id')});
throw new HttpError(404,'API endpoint не найден')}
const match=path.match(/^\/api\/tasks\/([a-z0-9-]+)$/);if(!match)throw new HttpError(404,'API endpoint не найден');let body;try{body=await request.json()}catch{throw new HttpError(400,'Некорректный JSON')}if(!body||typeof body.completed!=='boolean'||Object.keys(body).some(k=>k!=='completed'))throw new HttpError(400,'Передайте только completed: true или false');const task=await db.prepare('SELECT * FROM tasks WHERE id=?').bind(match[1]).first();if(!task)throw new HttpError(404,'Задача не найдена');await db.prepare('UPDATE tasks SET completed=? WHERE id=?').bind(body.completed?1:0,match[1]).run();return json({...task,completed:body.completed?1:0})}
export default{async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env);if(request.method!=='GET'&&request.method!=='HEAD')return json({error:'Метод не поддерживается'},405);const asset=ASSETS[url.pathname==='/'?'/index.html':url.pathname];if(!asset)return json({error:'Страница не найдена'},404);return new Response(request.method==='HEAD'?null:asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}})}catch(error){console.error('API error:',error.message);return json({error:error instanceof HttpError?error.message:'Не удалось загрузить или сохранить данные'},error.status||503)}}};
